### ISSUE TITLE
undefined in gulp output

### ISSUE THREAD

**Issue by vvhsk** [MitMaro/gulp-task-help#4]
gulpfile.js code: 
``` 
var gulp    = require( 'gulp' )
    , args    = require( 'yargs' ).argv 
    , Help    = require( 'gulp-task-help' );

var help = new Help(
    'myProject',
    'Description'
);

help.registerArgument(
  'arg1', 
  'some arguments',
  'default'
);

help.registerArgument(
  'arg2', 
  'some arguments', 
  'default'
);

help.registerTask( 'clean', 'cleans directory' );
help.registerTask( 'css', 'css task' );
help.registerTask( 'js', 'js task' );

help.registerTask(
  'build',
  'builds static',
  [ 'clean', 'js', 'css' ],
  [ ]
);

gulp.task( 'help', help.helpTask );

```

Output of gulp has undefined after every help variable reference:

![](https://i.gyazo.com/5297eff176e1949cb1e892f5ca0ecbf0.png)

**Comment by vvhsk** [comment]
I have gulp-cli 1.2.2 and local gulp 3.9.1.
No problem on machine with gulp-cli 3.9.1 and local gulp 3.9.1.

**Comment by MitMaro** [comment]
I only tested the project with gulp-cli > 3, so that is more than likely the problem. Try updating the machine running gulp 1.2.2 using `npm update gulp -g`.

**Comment by vvhsk** [comment]
Works fine with 3.9.1
